### ISSUE TITLE
Invalid tty in xterm

### ISSUE THREAD

**Issue by ghost** [dopsi/console-tdm#2] opened 2017-01-16 13:27 UTC
Hi,
Thanks for maintaining TDM!

I have just installed the program. Everything seems ok, except a warning in red: Invalid tty in my Xterm terminal when using Xorg.

Do you know what file i have to look for something?
Have a great day!

**Comment by dopsi** [comment] 2017-01-16 22:10
The invalid tty warning comes from [this line](https://github.com/dopsi/console-tdm/blob/master/tdm#L71). It means you are not in an actual TTY but in a virtual terminal (the output of the `tty` command will probably be `/dev/pts/<insert some number here>`).

This means you are already running Xorg and is not how TDM was designed (it is supposed to be a wrapper script for `startx`([see the man page](https://linux.die.net/man/1/startx)).

**Comment by mwgrient** [comment] 2017-01-17 09:14
I see, I had systemd told to login automatically for me as a regular user and start console-tdm. This is probably the case. Thanks.

**Comment by rosenpin** [comment] 2018-08-15 18:48
This also happens when using tmux which is pretty annoying, is there any way to disable this message?

**Comment by dopsi** [comment] 2018-09-11 17:09
There is no way as of yet. The way I do it is within a condition block

    if [ -n "$TMUX" ] ; then
      # do all of the tmux config
    else
      # do all of the non-tmux stuff
    fi

It never bothered me because I have a few other things to configure this way anyway, but I'd accept a PR similar to the commit that closed issue #18 (see commit 00a55cce).

**Comment by dopsi** [comment] 2018-09-22 07:39
Fixed in d95f2a4

**Closed by dopsi** 2018-09-22 07:39 UTC
